# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(30)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    try:
      self.driver.get("https://www.j-platpat.inpit.go.jp/s0100")
      self.driver.set_window_size(1552, 840)
      self.driver.find_element(By.ID, "s01_srchCondtn_txtSimpleSearch").click()
      self.driver.find_element(By.ID, "s01_srchCondtn_txtSimpleSearch").send_keys("ガバナンスクラウド")
      self.driver.find_element(By.CSS_SELECTOR, "#s01_srchBtn_btnSearch > span").click()
      time.sleep(5)
      assert self.driver.find_element(By.ID, "patentUtltyIntnlDocLst_searchResultMsg").text == "検索結果は0件でした。検索条件を変更して、再度検索を行ってください。"
      print("No patent found")  
    except Exception as e:
      print("something happens. please check!!")  
      

testobj = Test()
testobj.setup_method(None)
testobj.test_()
testobj.teardown_method(None)
answer = input("Press any key")